### ISSUE TITLE
How do I use in an app?

### ISSUE THREAD

**Issue by chabgood** [m4c3/omniauth-microsoft_graph#2]
Hi, i put the middleware in my app but how do I send emails?

**Comment by m4c3** [comment]
Hi, you mean how to get the users email address from the session information?

**Comment by chabgood** [comment]
No, we have an app in prod emailing, how do we send emails via rails?  We have to convert from smtp to graph api.

**Comment by m4c3** [comment]
ok, this gem can not help you with that.
checkout https://github.com/Mailbutler/mail_xoauth2

**Comment by m4c3** [comment]
depending on your needs, you can use the users oauth token that you already got from this gem or fetch a dedicated token like this https://gist.github.com/Overbryd/0ae6287b02a9848e5b67
